/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface NomadxSkipLink {
      /**
       * 5. Public Property API
       */
      'to': string;
    }
  }

  interface HTMLNomadxSkipLinkElement extends StencilComponents.NomadxSkipLink, HTMLStencilElement {}

  var HTMLNomadxSkipLinkElement: {
    prototype: HTMLNomadxSkipLinkElement;
    new (): HTMLNomadxSkipLinkElement;
  };
  interface HTMLElementTagNameMap {
    'nomadx-skip-link': HTMLNomadxSkipLinkElement;
  }
  interface ElementTagNameMap {
    'nomadx-skip-link': HTMLNomadxSkipLinkElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'nomadx-skip-link': JSXElements.NomadxSkipLinkAttributes;
    }
  }
  namespace JSXElements {
    export interface NomadxSkipLinkAttributes extends HTMLAttributes {
      /**
       * 5. Public Property API
       */
      'to'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;