/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface MarbleTable {
      'data': any[][];
      'labelledby': string;
      'sortable': string;
      'striped': any;
    }
  }

  interface HTMLMarbleTableElement extends StencilComponents.MarbleTable, HTMLStencilElement {}

  var HTMLMarbleTableElement: {
    prototype: HTMLMarbleTableElement;
    new (): HTMLMarbleTableElement;
  };
  interface HTMLElementTagNameMap {
    'marble-table': HTMLMarbleTableElement;
  }
  interface ElementTagNameMap {
    'marble-table': HTMLMarbleTableElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'marble-table': JSXElements.MarbleTableAttributes;
    }
  }
  namespace JSXElements {
    export interface MarbleTableAttributes extends HTMLAttributes {
      'data'?: any[][];
      'labelledby'?: string;
      'sortable'?: string;
      'striped'?: any;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;